name: Database CI/CD

on:
  push:
    branches:
      - main  # or your desired branch name
  pull_request:
    branches:
      - main  # or your desired branch name

jobs:
  database-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Run Database Migration
        run: |
          mysql -h database-1.cxozhkjis66j.ap-south-1.rds.amazonaws.com -P 3306 -u admin -p'Pushpa2#2024' -e "source ./db-scripts/001_create_users_table.sql"
          mysql -h database-1.cxozhkjis66j.ap-south-1.rds.amazonaws.com -P 3306 -u admin -p'Pushpa2#2024' -e "source ./db-scripts/002_create_active_users_view.sql"
          mysql -h database-1.cxozhkjis66j.ap-south-1.rds.amazonaws.com -P 3306 -u admin -p'Pushpa2#2024' -e "source ./db-scripts/003_create_get_user_details_procedure.sql"
