name: Database CI/CD

on:
  push:
    branches:
      - main  # or your desired branch name
  pull_request:
    branches:
      - main  # or your desired branch name

jobs:
  database-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL client
        run: sudo apt-get install mysql-client

      - name: Deploy SQL Scripts
        run: |
          # Run all SQL files in the db-scripts directory
          for file in ./db-scripts/*.sql; do
            echo "Running migration script: $file"
            mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source $file"
          done
