name: Database CI/CD

on:
  push:
    branches:
      - main  # or your desired branch name
  pull_request:
    branches:
      - main  # or your desired branch name

jobs:
  database-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run Database Migration
        run: |
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source ./db-scripts/001_create_users_table.sql"
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source ./db-scripts/002_create_active_users_view.sql"
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source ./db-scripts/003_create_get_user_details_procedure.sql"
